name: Flex
markdown: kramdown
highlighter: pygments

# Custom directory paths
layouts_dir: src/_layouts
data_dir: src/_data
includes_dir: src/_includes

exclude: 
  - LICENSE
  - README.md
  - script.sh
  - Gruntfile.js
  - manifest.json
  - package-lock.json
  - package.json
  - service-worker.js
  - convert_food_data.py
  - dist
  - 404.html

baseurl: ""
permalink: /:basename.html


# plugins:
#   - jekyll-polyglot


# jekyll-multiple-languages-plugin settings:
# languages: ["fr", "en", "ch"]
default_lang: "fr"

exclude_from_localization: ["docs", "node-modules", "css","src/media"]

parallel_localization: true

lang_from_path: true