name: Flex
markdown: kramdown
highlighter: pygments

# Set source directory
source: src

# Custom directory paths (relative to source)
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes

exclude: 
  - LICENSE
  - README.md
  - script.sh
  - Gruntfile.js
  - manifest.json
  - package-lock.json
  - package.json
  - service-worker.js
  - convert_food_data.py
  - dist
  - 404.html

baseurl: ""
permalink: /:basename.html

# Language settings
languages: ["fr", "en"]
default_lang: "fr"
exclude_from_localization: ["js", "css", "media", "data"]